[package]
name = "lowcat"
version = "1.1.2"
edition = "2024"
description = "A lightweight local sound library app."

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe", features = ["font-kit"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "8e4930fd687da9133bac06fdc0789e6a179f948c" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "8e4930fd687da9133bac06fdc0789e6a179f948c" }
futures = "0.3.32"
lofty = "0.24.0"
open = "5"
rodio = { version = "0.22.2", default-features = false, features = ["playback", "flac", "mp3", "wav"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite", "runtime-async-std"] }
symphonia = { version = "0.5.5", default-features = false, features = ["ogg"] }
symphonia-adapter-libopus = "0.2.9"
toml = "0.8.23"
trash = { version = "5.2", default-features = false, features = ["coinit_multithreaded"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2"
raw-window-handle = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
drag = "2.1.1"
raw-window-handle = "0.6"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.61"
winreg = "0.55"

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe", features = ["test-support"] }

[package.metadata.packager]
productName = "Lowcat"
identifier = "me.debuxxed.lowcat"
before-packaging-command = "cargo build --release"
icons = ["assets/logo.png"]

[package.metadata.packager.macos]
infoPlistPath = "packaging/macos/Info.plist"
signingIdentity = "-"
